/**
 * One-off script: converts mock.json seed data into seed.sql.
 * Run once:  bun run scripts/convert-seed.ts
 * Output:     src/data/seed/seed.sql
 *
 * Converts all 17 collections to literal INSERT statements.
 * Booleans → 0/1, dates → ISO strings, nested objects → JSON blobs.
 * SQL strings use '' escaping for apostrophes.
 */
import { writeFileSync } from 'fs';

const mock = require('/tmp/mock.json') as {
  workspaces: Array<{ id: string; name: string; initials: string; avatarColor?: string }>;
  currentWorkspaceId: string;
  projects: Array<{
    id: string; workspaceId: string; title: string; description: string;
    successCriteria: string; color: string; status: string;
    tickets: Array<{ id: string; title: string; status: string; assignedAgentId: string }>;
    agents: Array<{ id: string; name: string; role: string; currentStatus: string; assignedTicketId: string | null; initials: string }>;
    channels: Array<{ id: string; participants: string[]; topic: string; relatedTicketId: string; status: string; lastMessagePreview: string; messageCount: number; updatedAt: string; unread?: boolean; workspaceId?: string }>;
    activity: Array<{ id: string; timestamp: string; primaryAgent: string; action: string; targetAgent: string; context: string }>;
  }>;
  agents: Array<{ id: string; name: string; role: string; status: string; activeTask: string; uptime: string }>;
  universalTickets: Array<{
    id: string; title: string; projectName: string; workspaceId: string;
    status: string; priority: string; type: string;
    assignee: { name: string; avatarUrl?: string; isAI: boolean };
  }>;
  telemetry: Record<string, {
    contextSaturation: number; tokensPerSecond: number; currentCost: number;
    evolutionLoop: string; logicKernelIntegrity: number; sessionCost: number; budget: number;
  }>;
  permissions: Record<string, {
    modelEngine: string; writeAccess: boolean; commitAuthority: string;
    maxTokens: number; writeMessages: boolean; installDeps: boolean;
  }>;
  actionLogs: Record<string, Array<{ time: string; action: string }>>;
  nextSteps: Record<string, string>;
  auditItems: Array<{
    id: string; type: string; title: string; description: string;
    timestamp: string; agentId: string; scope?: string; prId?: string; touchedFiles?: number;
  }>;
  pendingQuestions: Array<{
    id: string; agentId: string; threadId?: string; messageId?: string;
    question: string; options?: string[]; timestamp: string;
  }>;
  chatThreads: Array<{
    id: string; title: string; agentId?: string;
    messages: Array<{ id: string; role: string; content: string; minutesAgo: number; model?: string; tokenCount?: number; durationMs?: number }>;
    updatedAtMinutesAgo: number;
  }>;
  favorites: Array<{ id: string; type: string }>;
  channelMessages: Array<{ id: string; channelId: string; senderName: string; content: string; timestamp: string; isAI: boolean }>;
  costUsage: Array<{ date: string; cost: number }>;
  chatQuickStart: Array<{ icon: string; label: string; description: string; category: string }>;
  customThemes: Array<{ id: string; name: string; vars: Record<string, string>; systemVars?: Record<string, string> }>;
  homeActivityEvents: Array<{
    id: string; kind: string; workspaceId: string; timestamp: string;
    actor: string; actorId?: string; target?: string; message: string;
    ref?: { type: string; id: string; workspaceId?: string };
  }>;
};

function s(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  const str = String(v);
  return "'" + str.replace(/'/g, "''") + "'";
}

function json(v: unknown): string {
  return "'" + JSON.stringify(v).replace(/'/g, "''") + "'";
}

function b(v: boolean): string {
  return v ? '1' : '0';
}

const now = Date.now();
let sql = '-- Superhive seed data — generated by scripts/convert-seed.ts\n';
sql += '-- Do not edit by hand; re-run the script after editing mock.json\n\n';

// meta
sql += `-- meta\n`;
sql += `INSERT INTO meta (key, value) VALUES (${s('currentWorkspaceId')}, ${s(mock.currentWorkspaceId)});\n`;
sql += `INSERT INTO meta (key, value) VALUES (${s('seeded')}, ${s('1')});\n\n`;

// workspaces
sql += `-- workspaces\n`;
for (const w of mock.workspaces) {
  sql += `INSERT INTO workspaces (id, name, initials, avatarColor) VALUES (${s(w.id)}, ${s(w.name)}, ${s(w.initials)}, ${s(w.avatarColor ?? null)});\n`;
}
sql += '\n';

// projects — JSON blob
sql += `-- projects\n`;
for (const p of mock.projects) {
  sql += `INSERT INTO projects (id, workspaceId, data) VALUES (${s(p.id)}, ${s(p.workspaceId)}, ${json(p)});\n`;
}
sql += '\n';

// agents
sql += `-- agents\n`;
for (const a of mock.agents) {
  sql += `INSERT INTO agents (id, name, role, status, activeTask, uptime) VALUES (${s(a.id)}, ${s(a.name)}, ${s(a.role)}, ${s(a.status)}, ${s(a.activeTask)}, ${s(a.uptime)});\n`;
}
sql += '\n';

// universal_tickets
sql += `-- universal_tickets\n`;
for (const t of mock.universalTickets) {
  sql += `INSERT INTO universal_tickets (id, title, projectName, workspaceId, status, priority, type, assigneeName, assigneeAvatarUrl, assigneeIsAI) VALUES (${s(t.id)}, ${s(t.title)}, ${s(t.projectName)}, ${s(t.workspaceId)}, ${s(t.status)}, ${s(t.priority)}, ${s(t.type)}, ${s(t.assignee.name)}, ${s(t.assignee.avatarUrl ?? null)}, ${b(t.assignee.isAI)});\n`;
}
sql += '\n';

// chat_threads — normalize minutesAgo, JSON-blob messages
sql += `-- chat_threads\n`;
for (const t of mock.chatThreads) {
  const updatedAt = new Date(now - t.updatedAtMinutesAgo * 60_000).toISOString();
  const msgs = t.messages.map(m => ({
    id: m.id,
    role: m.role,
    content: m.content,
    timestamp: new Date(now - m.minutesAgo * 60_000).toISOString(),
    model: m.model ?? null,
    tokenCount: m.tokenCount ?? null,
    durationMs: m.durationMs ?? null,
  }));
  sql += `INSERT INTO chat_threads (id, title, agentId, updatedAt, messages) VALUES (${s(t.id)}, ${s(t.title)}, ${s(t.agentId ?? null)}, ${s(updatedAt)}, ${json(msgs)});\n`;
}
sql += '\n';

// favorites
sql += `-- favorites\n`;
for (const f of mock.favorites) {
  sql += `INSERT INTO favorites (id, type) VALUES (${s(f.id)}, ${s(f.type)});\n`;
}
sql += '\n';

// custom_themes
sql += `-- custom_themes\n`;
for (const t of mock.customThemes) {
  sql += `INSERT INTO custom_themes (id, name, vars, systemVars) VALUES (${s(t.id)}, ${s(t.name)}, ${json(t.vars)}, ${t.systemVars ? json(t.systemVars) : 'NULL'});\n`;
}
sql += '\n';

// home_activity_events
sql += `-- home_activity_events\n`;
for (const ev of mock.homeActivityEvents) {
  sql += `INSERT INTO home_activity_events (id, kind, workspaceId, timestamp, actor, actorId, target, message, refType, refId, refWorkspaceId) VALUES (${s(ev.id)}, ${s(ev.kind)}, ${s(ev.workspaceId)}, ${s(ev.timestamp)}, ${s(ev.actor)}, ${s(ev.actorId ?? null)}, ${s(ev.target ?? null)}, ${s(ev.message)}, ${s(ev.ref?.type ?? null)}, ${s(ev.ref?.id ?? null)}, ${s(ev.ref?.workspaceId ?? null)});\n`;
}
sql += '\n';

// telemetry
sql += `-- telemetry\n`;
for (const [agentId, t] of Object.entries(mock.telemetry)) {
  sql += `INSERT INTO telemetry (agentId, contextSaturation, tokensPerSecond, currentCost, evolutionLoop, logicKernelIntegrity, sessionCost, budget) VALUES (${s(agentId)}, ${t.contextSaturation}, ${t.tokensPerSecond}, ${t.currentCost}, ${s(t.evolutionLoop)}, ${t.logicKernelIntegrity}, ${t.sessionCost}, ${t.budget});\n`;
}
sql += '\n';

// permissions
sql += `-- permissions\n`;
for (const [agentId, p] of Object.entries(mock.permissions)) {
  sql += `INSERT INTO permissions (agentId, modelEngine, writeAccess, commitAuthority, maxTokens, writeMessages, installDeps) VALUES (${s(agentId)}, ${s(p.modelEngine)}, ${b(p.writeAccess)}, ${s(p.commitAuthority)}, ${p.maxTokens}, ${b(p.writeMessages)}, ${b(p.installDeps)});\n`;
}
sql += '\n';

// action_logs — normalize to ISO timestamps (original is already ISO)
sql += `-- action_logs\n`;
for (const [agentId, entries] of Object.entries(mock.actionLogs)) {
  for (const entry of entries) {
    sql += `INSERT INTO action_logs (id, agentId, time, action) VALUES (${s(crypto.randomUUID())}, ${s(agentId)}, ${s(entry.time)}, ${s(entry.action)});\n`;
  }
}
sql += '\n';

// next_steps
sql += `-- next_steps\n`;
for (const [agentId, step] of Object.entries(mock.nextSteps)) {
  sql += `INSERT INTO next_steps (agentId, step) VALUES (${s(agentId)}, ${s(step)});\n`;
}
sql += '\n';

// cost_usage
sql += `-- cost_usage\n`;
for (const c of mock.costUsage) {
  sql += `INSERT INTO cost_usage (date, cost) VALUES (${s(c.date)}, ${c.cost});\n`;
}
sql += '\n';

// audit_items
sql += `-- audit_items\n`;
for (const a of mock.auditItems) {
  sql += `INSERT INTO audit_items (id, type, title, description, timestamp, agentId, scope, prId, touchedFiles) VALUES (${s(a.id)}, ${s(a.type)}, ${s(a.title)}, ${s(a.description)}, ${s(a.timestamp)}, ${s(a.agentId)}, ${s(a.scope ?? null)}, ${s(a.prId ?? null)}, ${a.touchedFiles ?? null});\n`;
}
sql += '\n';

// pending_questions
sql += `-- pending_questions\n`;
for (const q of mock.pendingQuestions) {
  sql += `INSERT INTO pending_questions (id, agentId, threadId, messageId, question, options, timestamp) VALUES (${s(q.id)}, ${s(q.agentId)}, ${s(q.threadId ?? null)}, ${s(q.messageId ?? null)}, ${s(q.question)}, ${q.options ? json(q.options) : 'NULL'}, ${s(q.timestamp)});\n`;
}
sql += '\n';

// channel_messages
sql += `-- channel_messages\n`;
for (const m of mock.channelMessages) {
  sql += `INSERT INTO channel_messages (id, channelId, senderName, content, timestamp, isAI) VALUES (${s(m.id)}, ${s(m.channelId)}, ${s(m.senderName)}, ${s(m.content)}, ${s(m.timestamp)}, ${b(m.isAI)});\n`;
}
sql += '\n';

// chat_quick_start
sql += `-- chat_quick_start\n`;
for (const q of mock.chatQuickStart) {
  sql += `INSERT INTO chat_quick_start (id, icon, label, description, category) VALUES (${s(crypto.randomUUID())}, ${s(q.icon)}, ${s(q.label)}, ${s(q.description)}, ${s(q.category)});\n`;
}
sql += '\n';

writeFileSync('src/data/seed/seed.sql', sql);
console.log('seed.sql written');
